name: Deploy to Server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy modules to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Navigate to custom modules directory (now the git repository)
          cd /var/www/html/drupal/modules/custom
          
          # Configure git safe directory
          git config --global --add safe.directory /var/www/html/drupal/modules/custom
          
          # Set ownership to ubuntu for git operations
          sudo chown -R ubuntu:ubuntu .git
          sudo chown -R ubuntu:ubuntu .
          
          # Pull the latest changes
          git fetch origin main
          git reset --hard origin/main
          
          # Set proper permissions for both modules
          sudo chown -R ubuntu:ubuntu .git
          sudo chown -R www-data:www-data news_extractor ai_conversation
          sudo find news_extractor -type f -exec chmod 644 {} \;
          sudo find news_extractor -type d -exec chmod 755 {} \;
          sudo find ai_conversation -type f -exec chmod 644 {} \;
          sudo find ai_conversation -type d -exec chmod 755 {} \;
          
          echo "Both modules deployed successfully"
          
    - name: Clear Drupal cache
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Fix file permissions for Drupal files directory
          sudo chown -R www-data:www-data /var/www/html/drupal/sites/default/files
          sudo find /var/www/html/drupal/sites/default/files -type f -exec chmod 664 {} \;
          sudo find /var/www/html/drupal/sites/default/files -type d -exec chmod 775 {} \;
          
          # Clear Drupal cache as www-data user
          cd /var/www/html/drupal
          sudo -u www-data drush cr
