name: Deploy to Server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy news_extractor module
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www/html/drupal/modules/custom/news_extractor
          git config --global --add safe.directory /var/www/html/drupal/modules/custom/news_extractor
          # Set ownership to ubuntu for git operations
          sudo chown -R ubuntu:ubuntu .
          # Pull the latest changes
          git fetch origin main
          git reset --hard origin/main
          # Set ownership back to www-data for web server
          sudo chown -R www-data:www-data .
          # Set permissions but exclude .git directory from www-data ownership
          sudo find . -name ".git" -prune -o -type f -exec chmod 644 {} \;
          sudo find . -name ".git" -prune -o -type d -exec chmod 755 {} \;
          # Keep .git directory accessible to ubuntu user
          sudo chown -R ubuntu:ubuntu .git
          
    - name: Deploy ai_conversation module
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Create temporary directory for clone
          TEMP_DIR="/tmp/ai_conversation_deploy_$(date +%s)"
          mkdir -p "$TEMP_DIR"
          cd "$TEMP_DIR"
          
          # Clone the repository
          git clone https://github.com/yourusername/your-repo-name.git .
          
          # Create ai_conversation directory if it doesn't exist
          sudo mkdir -p /var/www/html/drupal/modules/custom/ai_conversation
          
          # Copy ai_conversation files to the target directory
          sudo cp -r ai_conversation/* /var/www/html/drupal/modules/custom/ai_conversation/
          
          # Clean up temporary directory
          rm -rf "$TEMP_DIR"
          
          # Set proper ownership and permissions
          cd /var/www/html/drupal/modules/custom/ai_conversation
          sudo chown -R www-data:www-data .
          sudo find . -type f -exec chmod 644 {} \;
          sudo find . -type d -exec chmod 755 {} \;
          
    - name: Clear Drupal cache
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Clear Drupal cache
          drush cr
