name: Deploy to Server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy modules to server
      uses: appleboy/ssh-action@v0.1.5
      env:
        HUBGIT_PAT: ${{ secrets.HUBGIT_PAT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        envs: HUBGIT_PAT
        script: |
          set -e  # Exit on any error
          
          echo "=== Starting deployment ==="
          
          # Create a temporary directory for the repository
          TEMP_DIR="/tmp/thetruthperspective-deploy-$(date +%s)"
          mkdir -p "$TEMP_DIR"
          
          # Clone the repository to temp directory
          cd "$TEMP_DIR"
          git clone https://${HUBGIT_PAT}@github.com/keithaumiller/thetruthperspective.git .
          
          echo "=== Repository cloned to temp directory ==="
          echo "Files in repository:"
          ls -la
          
          # Copy only our specific modules to the custom modules directory
          CUSTOM_MODULES_DIR="/var/www/html/drupal/modules/custom"
          
          # Copy each module individually, preserving other modules
          echo "=== Copying news_extractor module ==="
          sudo rm -rf "$CUSTOM_MODULES_DIR/news_extractor"
          sudo cp -r news_extractor "$CUSTOM_MODULES_DIR/"
          
          echo "=== Copying newsmotivationmetrics module ==="
          sudo rm -rf "$CUSTOM_MODULES_DIR/newsmotivationmetrics"
          sudo cp -r newsmotivationmetrics "$CUSTOM_MODULES_DIR/"
          
          echo "=== Copying ai_conversation module ==="
          sudo rm -rf "$CUSTOM_MODULES_DIR/ai_conversation"
          sudo cp -r ai_conversation "$CUSTOM_MODULES_DIR/"
          
          echo "=== Copying job_application_automation module ==="
          sudo rm -rf "$CUSTOM_MODULES_DIR/job_application_automation"
          sudo cp -r job_application_automation "$CUSTOM_MODULES_DIR/"
          
          # Set proper permissions for all modules
          sudo chown -R www-data:www-data "$CUSTOM_MODULES_DIR/news_extractor"
          sudo chown -R www-data:www-data "$CUSTOM_MODULES_DIR/newsmotivationmetrics"
          sudo chown -R www-data:www-data "$CUSTOM_MODULES_DIR/ai_conversation"
          sudo chown -R www-data:www-data "$CUSTOM_MODULES_DIR/job_application_automation"
          
          sudo find "$CUSTOM_MODULES_DIR/news_extractor" -type f -exec chmod 644 {} \;
          sudo find "$CUSTOM_MODULES_DIR/news_extractor" -type d -exec chmod 755 {} \;
          sudo find "$CUSTOM_MODULES_DIR/newsmotivationmetrics" -type f -exec chmod 644 {} \;
          sudo find "$CUSTOM_MODULES_DIR/newsmotivationmetrics" -type d -exec chmod 755 {} \;
          sudo find "$CUSTOM_MODULES_DIR/ai_conversation" -type f -exec chmod 644 {} \;
          sudo find "$CUSTOM_MODULES_DIR/ai_conversation" -type d -exec chmod 755 {} \;
          sudo find "$CUSTOM_MODULES_DIR/job_application_automation" -type f -exec chmod 644 {} \;
          sudo find "$CUSTOM_MODULES_DIR/job_application_automation" -type d -exec chmod 755 {} \;
          
          echo "=== All modules deployed successfully ==="
          
          # === Copy custom node--article.html.twig to Olivero theme ===
          OLIVERO_PATH="/var/www/html/drupal/core/themes/olivero"
          CUSTOM_TWIG_SRC="$TEMP_DIR/news_extractor/templates/node--article.html.twig"
          CUSTOM_TWIG_DEST="$OLIVERO_PATH/templates/node--article.html.twig"
          sudo mkdir -p "$OLIVERO_PATH/templates"
          if [ -f "$CUSTOM_TWIG_SRC" ]; then
            sudo cp "$CUSTOM_TWIG_SRC" "$CUSTOM_TWIG_DEST"
            sudo chown www-data:www-data "$CUSTOM_TWIG_DEST"
            sudo chmod 644 "$CUSTOM_TWIG_DEST"
            echo "Custom node--article.html.twig copied to Olivero theme."
          else
            echo "Custom node--article.html.twig not found at $CUSTOM_TWIG_SRC"
          fi
          
          # Clean up temp directory
          rm -rf "$TEMP_DIR"
          echo "=== Cleanup completed ==="

    - name: Clear Drupal cache
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          set -e  # Exit on any error
          
          echo "=== Clearing Drupal cache ==="
          
          # Fix file permissions for Drupal files directory
          sudo chown -R www-data:www-data /var/www/html/drupal/sites/default/files
          sudo find /var/www/html/drupal/sites/default/files -type f -exec chmod 664 {} \;
          sudo find /var/www/html/drupal/sites/default/files -type d -exec chmod 775 {} \;
          
          # Clear Drupal cache as www-data user
          cd /var/www/html/drupal
          if ! sudo -u www-data drush cr; then
            echo "ERROR: Failed to clear Drupal cache"
            exit 1
          fi
          
          echo "=== Cache cleared successfully ==="
